spring:
  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html


  mvc:
    static-path-pattern: /static/**
